#!/bin/bash
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
nohup php run.php &
